### ISSUE TITLE
don't set module.exports in non-standalone mode

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/browser-pack-flat#21]
browsers don't have module.exports.

should probably just remove this line:
https://github.com/goto-bus-stop/browser-pack-flat/blob/5a8f7317e3dbc3846ac648c6c85ce7449509fc6f/index.js#L248

**Comment by goto-bus-stop** [comment]
#22

**Comment by heri16** [comment]
This seems to be affecting AWS lambda functions causing handle functions to sometimes not be exported on non-standalone mode.

**Comment by goto-bus-stop** [comment]
that's right, browserify bundles don't export anything in non standalone mode. to make them export things you have to use standalone mode.

(this change ensured that browser-pack-flat has the same behaviour as the default browser-pack.)
