### ISSUE TITLE
Rewrote getter bug

### ISSUE THREAD

**Issue by heri16** [goto-bus-stop/browser-pack-flat#28]
Tried running this plugin on node-fetch-npm .

This https://github.com/npm/node-fetch-npm/blob/3fe74ce68c545a5de650c54e76e7e249c9af8d45/src/request.js#L95
```javascript
class Request {
  get url () {
    return url.format(this[PARSED_URL])
  }
}
```

Gets rewritten to:
```javascript
class Request {
  get __url_153 () {
    return __url_153.format(this[PARSED_URL])
  }
}
```

Which causes undefined error, when trying to access response.url in `make-fetch-happen`.

**Comment by goto-bus-stop** [comment]
thanks! this is fixed by scope-analyzer@2.0.4; doing `npm update` should get it.
